[#177241417] Set OOM-Score in Systemd when value is defined
Rheinwerk/ansible-role-update_scollector_config pull request #1
Opened 2021-03-08 11:39 UTC by eifelmicha

2021-03-08 11:39 UTC, eifelmicha commented
@aberresch 
requesting review.
requesting functional acceptance.

2021-03-08 14:20 UTC, aberresch requested changes
Siehe Kommentare

2021-03-08 14:20 UTC, aberresch commented on tasks/main.yml
> +        daemon_reexec: yes
Warum `daemon_reexec` und nicht `daemon_reload`?

2021-03-08 14:20 UTC, aberresch commented on tasks/main.yml
> +      when: stat_scollector_override.stat.exists
Bedeutet das jetzt, dass dieses Feature nicht benutzt werden kann wenn keine `override` Datei existiert?

2021-03-09 08:59 UTC, eifelmicha commented on tasks/main.yml
> +      when: stat_scollector_override.stat.exists
Korrekt, alle unsere Systeme haben diese Datei.

2021-03-09 08:59 UTC, eifelmicha commented
@aberresch
requesting review.
requesting functional acceptance.

2021-03-09 14:14 UTC, aberresch approved these changes
Review: LGTM
Functionally accepted

2021-03-09 14:14 UTC, eifelmicha commented
@aberresch
requesting merge approval.

2021-03-09 14:15 UTC, merged